# A docker-compose must always start by the version tag.
version: '3.7'

# docker-composes works with services.
# 1 service = 1 container.
# For example, a service maybe, a server, a client, a database...
# We use the keyword 'services' to start to create services.
services:

  # First service (container): the backend app .

  # We use the keyword 'smartcow-app' for backend app .
  smartcow-app:
    # The keyword "build" will allow you to define
    # the path to the Dockerfile to use to create the image
    # that will allow you to execute the service.
    # Here 'api/' corresponds to the path to the api folder
    # that contains the Dockerfile to use.
    build: api/docker

    # The command to execute once the image is created.
    # The following command will execute "python ./app.py".
    # command: python ./app.py

    # In our case, we want to use port 5000 on our machine and
    ports:
      - "5000:5000"

    expose:
      - "5000"
    
    # push the images to localhost
    image : smartcow-app:latest
    # push the images to dockerhub/external docker registry 
    image : dkagitha/smartcow-app:latest
    
    # Add the command to serve the application via gunicorn
    # command: gunicorn -w 1 -b 0.0.0.0:5000 wsgi:server

  # Second service (container): the smartcow-ui.
  # We use the keyword 'smartcow-ui' for the server.
  smartcow-ui:
    # Here 'smartcow-ui/ corresponds to the path to the sys-stats folder
    # that contains the Dockerfile to use.
    build: sys-stats/docker

    # The command to execute once the image is created.
    # The following command will execute "npm start".

    # In our case, we want to use port 3000 on our machine and
    ports:
        - "3000:3000"

    expose:
      - "3000"
    
    # push the images to localhost
    image : smartcow-ui:latest
    # push the images to dockerhub/external docker registry 
    image : dkagitha/smartcow-ui:latest

    # The keyword'depends_on' allows you to define whether the service
    # should wait until other services are ready before launching.
    # Here, we want the 'client' service to wait until the 'server' service is ready.
    depends_on:
      - smartcow-app